TerraLindaHighSchool/memorium-memorium-production-team

Assets/Prefabs/Character/Player.prefab
Assets/Scripts/Player_Control/PlayerController.cs
Assets/Scripts/Player_Control/PlayerController.cs.meta
Assets/Scripts/Player_Control/README.txt.meta

Added Player controller script
Added CharacterController Component
Added LookAtTarget child object
Added GroundDetector child object

Complete Player Capsule

---

.idea/.idea.memorium-memorium-production-team/.idea/projectSettingsUpdater.xml
.idea/.idea.memorium-memorium-production-team/.idea/workspace.xml
Assets/Scenes/Testing_Scenes/CameraController_JRoberts.unity
Assets/Scenes/Testing_Scenes/CameraController_JRoberts.unity.meta

Merging PlayerController and CameraController into one integration branch so I can work on them.

Merge CameraController into Player+CameraController Integration Branch

---

.idea/.idea.memorium/.idea/.gitignore
.idea/.idea.memorium/.idea/encodings.xml
.idea/.idea.memorium/.idea/indexLayout.xml
.idea/.idea.memorium/.idea/vcs.xml
Assets/Prefabs/Puzzle/PuzzleSetObj.prefab
Assets/Prefabs/Puzzle/PuzzleSetObj.prefab.meta
Assets/Scenes/Testing_Scenes/PuzzleController_ECoskey.unity
Assets/Scenes/Testing_Scenes/PuzzleController_ECoskey.unity.meta
Assets/Scripts/Puzzle_Control/PuzzleController.cs
Assets/Scripts/Puzzle_Control/PuzzleController.cs.meta
Assets/Scripts/Puzzle_Control/PuzzleSet.cs
Assets/Scripts/Puzzle_Control/PuzzleSet.cs.meta

Puzzle Controller Complete

---

.idea/.idea.memorium-memorium-production-team/.idea/workspace.xml
Assets/Prefabs/Interface/UI/Cursor.prefab
Assets/Scenes/Testing_Scenes/PlayerController_JRoberts.unity
Assets/Scripts/Other/CursorController.cs
Assets/Scripts/Player_Control/PlayerController.cs
Assets/Scripts/Player_Control/PlayerInputActions.cs
Assets/playeractions.inputactions

Merging bug fixes back into develop. The cursor has to have a reference to the player for now because for some reason making a PlayerInputActions in the CursorController doesn't work. Possibly put input handling into some kind of manager class at some point in the future

Successfully combined things from the merge

---

Packages/packages-lock.json

needed an extra closing brace in package-lock.json

Fixed stupid unity import error

---

.idea/.idea.memorium-memorium-production-team/.idea/workspace.xml
Assets/Scripts/Camera_and_Lighting/CameraController.cs
Assets/Scripts/Player_Control/PlayerController.cs
Assets/Scripts/Puzzle_Control/PuzzleController.cs

I changed from the built-in Unity GUID package to the System.Guid package because I found *one* forum post saying that Unity Android builds have problems with the Unity GUID package and so I'm just hoping this might fix it

Fixed player gravity and hopefully GUID build issues

---

Assets/Scripts/Other/SpringBone.cs
Assets/Scripts/Other/SpringBone.cs.meta
Assets/Scripts/Other/SpringCollider.cs
Assets/Scripts/Other/SpringCollider.cs.meta
Assets/Scripts/Other/SpringManager.cs
Assets/Scripts/Other/SpringManager.cs.meta

Hair Bones and Stuffs are imported

---

.idea/.idea.memorium-memorium-production-team/.idea/workspace.xml
Assets/Scripts/Camera_and_Lighting/CameraController.cs
Assets/Scripts/Other/CursorController.cs
Assets/Scripts/Player_Control/PlayerController.cs
Assets/Scripts/Player_Control/PlayerInputManager.cs
Assets/Scripts/Player_Control/PlayerInputManager.cs.meta

a new singleton class for keeping the PlayerInputActions object.

Created PlayerInputManager

---

Assets/Scripts/Game_Managing/SceneManager.cs

Emer this is why we don't try and use declarative syntax in an imperative language space. It causes problems like this.

Fixed switch statement syntax

---

Assets/Prefabs/Environment/StainedGlassIslandGreybox.prefab
Packages/packages-lock.json
ProjectSettings/Packages/com.unity.probuilder/Settings.json
ProjectSettings/Packages/com.unity.progrids/Settings.json

Should be the island, and maybe a cypher wheel.

Feature stained glass island greybox grace kb

---

Assets/Scripts/Game_Managing/Game_Context/Cutscene/CutsceneContextController.cs
Assets/Scripts/Game_Managing/Game_Context/GameContextManager.cs
Assets/Scripts/Puzzle_Control/Puzzle2D/Pane2D.cs
Assets/Scripts/Puzzle_Control/Puzzle2D/PuzzleObject2D.cs
Assets/Scripts/Puzzle_Control/PuzzleSet.cs
ProjectSettings/Packages/com.unity.probuilder/Settings.json

some will still be there, but jackson fixed those on another branch

hopefully fixed build errrors

---

Assets/Art/Animation/Demons/Anger.meta~Develop.meta

Fixed flower island textures

---

Assets/Art/Animation/Demons/Anger.meta~Develop.meta
Assets/Art/Animation/FriendlyNPCs/SpiritYu/LeaveCage.fbx.meta
Assets/Art/Animation/FriendlyNPCs/SpiritYu/MergeWAmara.fbx.meta
Assets/Art/Animation/FriendlyNPCs/SpiritYu/MergeWSword.fbx.meta
Assets/Art/Particles.meta

Fixed Flower Island Ground Textures Again

---

Assets/Scripts/Object_Control/FlowerGateController.cs
Assets/Scripts/Puzzle_Control/LightPuzzle.meta

Feature/r hoang/flower island gate2

---

Assets/Scripts/Puzzle_Control/LightPuzzle/Folder.DotSettings.user.meta

fixed stained glass island

---

Assets/Art/Animation/Player/AmaraAnimController.controller
Assets/Scripts/Player_Control/PlayerController.cs

Animation Fixed

---

Assets/Art/Materials/Textures.meta
Assets/Art/Particles.meta
Assets/Prefabs/Character/Pactus.prefab
ProjectSettings/Packages/com.unity.probuilder/Settings.json

Gustin said I should add this.

Feature/m harrison/library lighting

---

Assets/Art/2-D Cutscenes.meta.orig.meta
Assets/Art/Particles.meta
Assets/Scripts/Puzzle_Control/LightPuzzle/Folder.DotSettings.user.meta

Fixed the gate by adding the interactable tag and layer. Also added the interactable script to the cylinders.

Gate Bug Fix

---

Assets/Art/Shaders/Amara Cloak.mat
Assets/Art/Shaders/Amara Cloak.mat.meta
Assets/Art/Shaders/TwoSidedLit.shader
Assets/Art/Shaders/TwoSidedLit.shader.meta
Assets/Prefabs/Character/Player.prefab

amara's hood now has its own fancy shader, how wonderful

Rejoice! The hood is two-sided!

---

Assets/Art/Animation/FriendlyNPCs/GrassBird/GrassBirdAnimController.controller
Assets/Scripts/NPC_Control/GrassBirdController.cs
Assets/Scripts/NPC_Control/NPC.cs

All grass birds need event recievers put on them but only tutorial island has birds rn anyway so whatever

Fixed grass bird anims
